name: Run unit tests on PR
on: 
  pull_request
defaults:
  run:
    shell: bash
    working-directory: plugins/woocommerce
jobs:
  test:
    name: PHP ${{ matrix.php }} WP ${{ matrix.wp }}
    timeout-minutes: 20
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.wp == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0' ]
        wp: [ "latest" ]
        include:
          - wp: nightly
            php: '7.4'
          - wp: '5.8'
            php: 7.2
          - wp: '5.7'
            php: 7.2
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
            access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: mysql
          coverage: none

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Get cached composer directories
        uses: actions/cache@v2
        with:
          path: |
            ./packages
            ./vendor
          key: ${{ runner.os }}-${{ hashFiles('./composer.lock') }}

      - name: Install PNPM and install dependencies
        run: |
            npm install -g pnpm
            pnpm install
            pnpm nx composer-install woocommerce

      - name: Build Admin feature config
        working-directory: ./
        run: |
          pnpm nx build:feature-config woocommerce

      - name: Add PHP8 Compatibility.
        run: |
          if [ "$(php -r "echo version_compare(PHP_VERSION,'8.0','>=');")" ]; then
             curl -L https://github.com/woocommerce/phpunit/archive/add-compatibility-with-php8-to-phpunit-7.zip -o /tmp/phpunit-7.5-fork.zip
             unzip -d /tmp/phpunit-7.5-fork /tmp/phpunit-7.5-fork.zip
             composer bin phpunit config --unset platform
             composer bin phpunit config repositories.0 '{"type": "path", "url": "/tmp/phpunit-7.5-fork/phpunit-add-compatibility-with-php8-to-phpunit-7", "options": {"symlink": false}}'
             composer bin phpunit require --dev -W phpunit/phpunit:@dev --ignore-platform-reqs
             rm -rf ./vendor/phpunit/
             composer dump-autoload
           fi

      - name: Prepare Test Environment
        run: |
          WP_VERSION="${{ matrix.wp }}"
          if [[ $WP_VERSION == 'latest' ]]; then
            WP_VERSION="null"
          elif [[ $WP_VERSION == 'nightly' ]]; then
            WP_VERSION="\"WordPress/WordPress#master\""
          else
            WP_VERSION="\"WordPress/WordPress#$WP_VERSION\""
          fi
          echo "{ \"phpVersion\": \"${{ matrix.php }}\", \"core\": $WP_VERSION }" > .wp-env.override.json

      - name: Run Tests
        run: |
          npm -g install @wordpress/env
          wp-env start
          pnpm nx test-unit woocommerce
